<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-09-01 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.6 on 2021-08-31 22:14

from django.db import migrations, models
>>>>>>> faa825e0e20d8693fde3de75d47c3683274fd48d


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> faa825e0e20d8693fde3de75d47c3683274fd48d
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='book_mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=900)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
>>>>>>> faa825e0e20d8693fde3de75d47c3683274fd48d
            ],
        ),
    ]
