# Generated by Django 3.2.6 on 2021-09-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_mark',
            name='user',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sender',
        ),
        migrations.DeleteModel(
            name='book_mark',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
