# Generated by Django 3.2.6 on 2021-08-31 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='media/%Y/%m/%d')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('MessagesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.messages')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
