// TYPES OF ACTION

export const GET_MEMBERS = "GET_MEMBERS";
export const CREATE_ROOM = "CREATE_ROOM";
export const GET_ROOMS = "GET_ROOMS";
export const GET_SOCKETS = "GET_SOCKETS";
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGE = "GET_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const GET_PINNED_MESSAGE = "GET_PINNED_MESSAGE";
export const MESSAGE_REACTION = "MESSAGE_REACTION";
export const GET_ROOM_MESSAGES = "GET_ROOM_MESSAGES";
export const PIN_MESSAGE = "PIN_MESSAGE";
export const UNPIN_MESSAGE = "UNPIN_MESSAGE";
export const GET_BOOKMARKS = "GET_BOOKMARKS";
export const ADD_TO_BOOKMARK = "ADD_TO_BOOKMARK";
