// TYPES OF ACTION

export const GET_MEMBERS = "GET_MEMBERS";
export const GET_MEMBER_PROFILE = "GET_MEMBER_PROFILE";
export const CREATE_ROOM = "CREATE_ROOM";
export const GET_ROOMS = "GET_ROOMS";
export const GET_ROOM_INFO = "GET_ROOM_INFO";
export const GET_ROOM_MESSAGES = "GET_ROOM_MESSAGES";
