// TYPES OF ACTION

export const GET_MEMBERS = "GET_MEMBERS";
export const GET_MEMBER_PROFILE = "GET_MEMBER_PROFILE";

export const SET_ROOM = "SET_ROOM";
export const CREATE_ROOM = "CREATE_ROOM";

export const GET_ROOMS = "GET_ROOMS";
export const GET_ROOM_INFO = "GET_ROOM_INFO";
export const GET_ROOM_MESSAGES = "GET_ROOM_MESSAGES";
export const CREATE_ROOM_MESSAGES = "CREATE_ROOM_MESSAGES";
export const DELETE_ROOM_MESSAGE = "DELETE_ROOM_MESSAGE";

export const GET_ALL_DMS = "GET_ALL_DMS";

export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
export const GET_LOGGED_IN_USER = "GET_LOGGED_IN_USER";
export const GET_LOGGED_IN_USER_ORGANISATION = "GET_LOGGED_IN_USER_ORGANISATION";
export const ADD_PEOPLE_TO_ROOM = "ADD_PEOPLE_TO_ROOM";
